version: "3.5"
services:
  neo4j:
    build: ./db/neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./db/docker_data:/data
      - ./log:/logs
  app:
    build: .
    environment:
      - RAILS_ENV=development
    command: rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    volumes:
      - .:/manga
